# Generated by Django 4.2.16 on 2024-11-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.TextField()),
                ('last_name', models.TextField()),
                ('gender', models.TextField()),
                ('pat_password', models.TextField()),
                ('pat_password_confirm', models.TextField(null=True)),
                ('phoneno', models.TextField()),
            ],
        ),
    ]
