# Generated by Django 4.2.16 on 2024-11-29 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_appoinmentmodels_delete_patientmodels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appoinmentmodels',
            name='pat_name',
        ),
    ]
