# Generated by Django 4.2.16 on 2024-11-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0003_remove_appoinmentmodels_pat_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appoinmentmodels',
            name='pat_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
